name: Create a new release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      releaseNumber:
        description: 'Release number'     
        required: true

jobs:
  createRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Check parameter
        run: |
          # Check parameter
          version=${{ github.event.inputs.releaseNumber }}
          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo Version v${version};
          else
            echo Invalid version number - $version;
            echo
            echo You must use the pattern
            echo major.minor.patch
            echo
            echo Examples:
            echo 0.20.1
            echo 1.0.3
            echo 2.5.0
            echo

            exit 1
          fi

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git config commmit user
        run: |
          # Git config commmit user
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config pull.rebase true

      - name: Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash $GITHUB_WORKSPACE/githubScripts/tag-release.sh ${{ github.event.inputs.releaseNumber }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.releaseNumber }}
          release_name: v${{ github.event.inputs.releaseNumber }}
          commitish: master
          draft: false
          prerelease: true

      - name: Wait release - Timeout 5 min
        run: timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' https://api.github.com/repos/jmoalves/levain/releases/tags/v${{ github.event.inputs.releaseNumber }})" != "200" ]]; do echo Waiting...; sleep 5; done' || false

      - name: Package and Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash $GITHUB_WORKSPACE/githubScripts/package-after-release.sh ${{ github.event.inputs.releaseNumber }} 
