name: Tag a new release

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      releaseNumber:
        description: 'Release number'     
        required: true

jobs:
  tagRelease:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Config commmit user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config pull.rebase true
      - name: Tag
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: bash $GITHUB_WORKSPACE/ci/tag-release.sh ${{ github.event.inputs.releaseNumber }}
