name: Run tests

on:
  #push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  runTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          denoTemp=$( mktemp -d )  
          bash $GITHUB_WORKSPACE/githubScripts/get-deno.sh $denoTemp
          export PATH=${denoTemp}:$PATH
          cd $GITHUB_WORKSPACE
          bash ./scripts/test.sh
          rm -rf ${denoTemp}
